### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [mozilla/webops-websec-guide#11]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/webops-websec-guide/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by floatingatoll** [comment]
I can't as I'm no longer a GitHub admin, but as sole author of the repo to date, I recommend disabling this repo's wiki entirely rather than restrict write access.

**Comment by ghost** [comment]
Hah - no one had write access. :)

I've disabled the wiki, and made you an admin -- you can drop privs if you want.
